BTable Sorting
cdmoro/bootstrap-vue-3 pull request #594
Opened 2022-08-28 12:24 UTC by devhus

supported props from vue-bootstrap:
- sort-by
- sort-desc

new props: 
-sort-internal{boolean} = a boolean to determine if you want the table to sort the given rows or not, it can be disabled when using an external API request for sorting your table

working example:
```vue
<template>
  <b-container>
    <div>
      <b-table
        :items="items"
        :fields="fields"
        v-model:sort-by="sortBy"
        v-model:sort-desc="sortDesc"
        :sort-internal="true"
      ></b-table>

      <div>
        Sorting By: <b>{{ sortBy }}</b>, Sort Direction:
        <b>{{ sortDesc ? 'Descending' : 'Ascending' }}</b>
      </div>
    </div>
  </b-container>
</template>

<script  lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data() {
    return {
      sortBy: 'age',
      sortDesc: false,
      fields: [
        { key: 'last_name', label: 'last_name', sortable: true },
        { key: 'first_name', label: 'first_name', sortable: true },
        { key: 'age', label: 'age', sortable: true },
        { key: 'isActive', label: 'isActive', sortable: false }
      ],
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson' },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
      ]
    }
  }
});
</script>
```

2022-08-28 23:00 UTC, VividLemon requested changes
Tomorrow, I will make a new branch, merge this into the new branch, then would like to review the behavior. (Since there are many changes to this component)

2022-08-28 23:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +              {'b-table-sortable-column': isSortable && field.sortable},
I'm not exactly sure if you can stuff an object into the array of classes. I know you can uses an object, or an array, but I don't know if you can do both. Double check this

2022-08-28 23:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +          :class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]"
If there's a single item in the array, it should be refactored to just be `:class="tr._rowVariant ? table-${tr._rowVariant} : null`

2022-08-28 23:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                <span v-show="sortDesc == true">▼</span>
eqeqeq!!! ☠️

2022-08-28 23:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +            :class="[
This array might be better off pulled into a computed method in <script>

2022-08-28 23:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                v-if="isSortable && field.sortable && field.key == sortBy"
eqeqeq

2022-08-29 00:45 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/_table.scss
> +.table.b-table > tbody > tr > .table-b-table-default,
Did not update that line, might be a formatter update.

2022-08-29 00:46 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +              {'b-table-sortable-column': isSortable && field.sortable},
The class name was updated on my screen, my guess is the array can also take an object.

2022-08-29 00:50 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +          :class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]"
I didn't get what you mean.

2022-08-29 00:51 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                <span v-show="sortDesc == true">▼</span>
what ?

2022-08-29 00:52 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                v-if="isSortable && field.sortable && field.key == sortBy"
The header should not have flex display ?

2022-08-29 00:54 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                v-if="isSortable && field.sortable && field.key == sortBy"
v-if="isSortable && field.sortable && field.key == sortBy" => v-if="isSortable && field.sortable && field.key === sortBy". Do not use ==, only use ===

2022-08-29 00:57 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/_table.scss
> +.table.b-table > tbody > tr > .table-b-table-default,
If you are talking about the ``.b-table-sortable-column`` selector, is to give a pointer cursor to the sortable headers so when you hover on the header it will show as it is "clickable"

2022-08-29 01:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +          :class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]"
:class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]" => :class="tr._rowVariant ? table-${tr._rowVariant} : null

2022-08-29 01:00 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                <span v-show="sortDesc == true">▼</span>
https://eslint.org/docs/latest/rules/eqeqeq
 v-if="isSortable && field.sortable && field.key == sortBy" =>  v-if="isSortable && field.sortable && field.key === sortBy"

2022-08-29 01:02 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                v-if="isSortable && field.sortable && field.key == sortBy"
Won't hurt since it's 100% a string-to-string comparison so it doesn't need a type check. Anyway, it was fixed.

2022-08-29 01:04 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +          :class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]"
Oh, That wasn't really my doing it was like that before my commits, I didn't want to change it since its not harming anyone xD

2022-08-29 01:06 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +          :class="[tr._rowVariant ? `table-${tr._rowVariant}` : null]"
Yeah it's not your fault, just a cleanup while it's being worked on

2022-08-29 01:08 UTC, devhus commented
@VividLemon Be aware that i've pushed another commit for BModal component as well.

2022-08-29 01:09 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/_table.scss
> +.table.b-table > tbody > tr > .table-b-table-default,
I meant more for what the change in this file was for

2022-08-29 01:11 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +                v-if="isSortable && field.sortable && field.key == sortBy"
Even if it's a string-string, shouldn't use ==. I'm shocked your eslint didn't stop you from doing that. I'm not 100%, but I'm fairly certain it would have been a failing action when I approve the workflow.

2022-08-29 01:12 UTC, VividLemon commented
> @VividLemon Be aware that i've pushed another commit for BModal component as well.

I'm aware. Honestly, I'm not exactly sure if we can use suspense 🤔 Not sure though.

2022-08-29 01:13 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/_table.scss
> +.table.b-table > tbody > tr > .table-b-table-default,
> I meant more for what the change in this file was for

my guess is spaces, might be the formatter updates to the file

2022-08-29 01:20 UTC, devhus commented
> > @VividLemon Be aware that i've pushed another commit for BModal component as well.
> 
> I'm aware. Honestly, I'm not exactly sure if we can use suspense 🤔 Not sure though. Probably can, I don't see why not...

I've tried to replace the suspense component with a template tag and nothing really changed, everything works fine with <suspense> or <template> 
https://www.loom.com/share/0b4663f2b0b04a9d8a639369397e2ef5

a working example: 
```vue
<template>
  <b-container>
    <div>
      <b-button
        variant="primary"
        @click="modal1 = true"
      >Nested Modal</b-button>
      <b-button
        variant="primary"
        @click="modal2 = true"
      >Lazy-load Modal</b-button>

      <b-modal
        v-model="modal1"
        title="Nestable Modal"
      >
        The modal below is nested, click to open it!
        <b-button
          @click="modal3 = true"
          variant="primary"
        >Open Nested Modal</b-button>
        <b-modal
          v-model="modal3"
          title="Nested Modal"
        >I am Nested!</b-modal>
      </b-modal>
      <b-modal
        v-model="modal2"
        title="Lazy-load Modal"
        lazy
        @shown="modalShown"
      >
        The content below is lazy-loaded, Might not load the content script from server but will not Mount the child
        component before the modal is opened.<br>
        Every time the modal opens the mounted event will be triggered for the child component.
        <test ref="modalContentComponent"></test>
      </b-modal>
    </div>
  </b-container>
</template>

<script  lang="ts" setup>
import { ref } from 'vue';
import Test from './Test.vue';

const modal1 = ref(false);
const modal2 = ref(false);
const modal3 = ref(false);

const modalContentComponent = ref();
const modalShown = () => {
  console.log('modalContentComponent is mounted ?', modalContentComponent.value.isMounted);
}
</script>
```

2022-08-29 01:20 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/_table.scss
> +.table.b-table > tbody > tr > .table-b-table-default,
It appears to have been a duplicated line, 
```scss
.table.b-table > tbody > tr > .table-b-table-default,
.table.b-table > tfoot > tr > .table-b-table-default,
.table.b-table > thead > tr > .table-b-table-default {
  color: #212529;
  background-color: #fff;
}

.table.b-table > tbody > tr > .table-b-table-default,
.table.b-table > tfoot > tr > .table-b-table-default,
.table.b-table > thead > tr > .table-b-table-default {
  color: #212529;
  background-color: #fff;
}
```

2022-08-29 01:21 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTableContainer.vue
> +  responsiveClasses: any
This wasn't resolved. Replace this and remove `any`

2022-08-29 01:34 UTC, VividLemon commented
I will review further tomorrow. But it's looking like some good changes, besides just some minor issues. Thanks for the additions.

2022-08-29 02:14 UTC, devhus commented
You are welcome, i hope the request merge to be done asap so i can use these updates on my company's prod app 😄
No pressure.

2022-08-29 19:01 UTC, VividLemon commented
BEGIN_COMMIT_OVERRIDE
feat(BTable): add sorting option props

feat(BModal): support lazy loading
END_COMMIT_OVERRIDE

2022-08-29 19:07 UTC, merged