BModal lazy prop improvement, BButton loading prop
cdmoro/bootstrap-vue-3 pull request #601
Opened 2022-08-29 23:15 UTC by devhus

**BModal lazy prop improvement**
- Included the BModal header & footer slots to be lazy-rendered, Which gives makes the component lazy-render work correctly when giving a component to the header/footer slots that require to be mounted after the modal was shown.
- Added an additional variable ``lazyLoadCompleted`` to make sure that the modal's lazy rendered content stays shown until the modal was fully hidden. 

Example of the lazy-rendered modal content on hide/close without the ``lazyLoadCompleted`` variable:
https://www.loom.com/share/e027cb1c0b674c53adbbf906737c0dc2

After adding  ``lazyLoadCompleted` variable & condition:
https://www.loom.com/share/2fc9bc3ce1694336822d34b6a936104c

**BButton loading prop**
- Added a new prop to BButton component giving it the ability to show a BSpiiner when needed, also added a few custom CSS attrs to the BSpinner element to render responsively with the button's size & bootstrap's ``fw-bold`` class.

BButton working example: 
```vue
<template>
  <b-container>
    <div class="d-flex gap-2 align-items-center">
      <b-button
        variant="primary"
        :loading="btnLoading"
        @click="btnLoading = !btnLoading"
        :size="'sm'"
      >Click to {{ btnLoading ? 'stop' : 'start' }} loading!</b-button>
      <b-button
        variant="primary"
        :loading="btnLoading"
        @click="btnLoading = !btnLoading"
        :size="'md'"
      >Click to {{ btnLoading ? 'stop' : 'start' }} loading!</b-button>
      <b-button
        variant="primary"
        :loading="btnLoading"
        @click="btnLoading = !btnLoading"
        :size="'lg'"
      >Click to {{ btnLoading ? 'stop' : 'start' }} loading!</b-button>
    </div>
  </b-container>
</template>

<script  lang="ts" setup>
import { ref } from 'vue';

const btnLoading = ref(false);
</script>
```

2022-08-29 23:22 UTC, VividLemon reviewed
Besides the one issue, I approve.

2022-08-29 23:22 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
I would convert this to instead be 
```vue
<slot name="loading">
    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'" />
</slot>
```
This would allow for people to specify how they want their loading spinner to be.

2022-08-29 23:22 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BModal.vue
> +        <div
Good addition to make the entire modal lazy loaded. I saw the same behavior of the modal not doing it's animation, so I decided not to touch the v-ifs at that time. 👍

2022-08-29 23:24 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/_button.scss
> +.btn {
Are you sure there's not some built in classes/props that could be used, instead of adding custom css?

2022-08-29 23:27 UTC, VividLemon commented
Please, if you intend to continue contributing, you will need to have your commit messages conform to [conventional commits](https://www.conventionalcommits.org/)

2022-08-30 01:34 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
I  thought about that but you already have access to the default slot where you can add your custom loading component and it works the same, for example:
```vue
<b-button>
<CustomLoaderComponentThatShowsWhenPropPassed :loading="true" />
Submit
</b-button>
```
Which seems to be much better then having a slot for it like that:
```vue
<b-button>
<template #loading>
<CustomLoaderComponent />
</template>
Submit
</b-button>
```
So, the loading prop on BButton works as a quick solution when you don't need a custom loader but you can still customize its style in your global CSS files as i did in the button's SCSS file

2022-08-30 01:37 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BButton/_button.scss
> +.btn {
I don't think there are any built-in classes/props to achieve the same result, As you can see it only overwrites the ``<BSpinner>`` component CSS to have sizes that fit with the button's size without touching the ``<BSpinner>``  logic/code for sizing.

2022-08-30 01:42 UTC, devhus commented
> Please, if you intend to continue contributing, you will need to have your commit messages conform to [conventional commits](https://www.conventionalcommits.org/)

I will take a look and try my best to follow it in any upcoming commits. Sorry if  i am doing something wrong, It's my first time contributing an open-source library.

2022-08-30 01:43 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
eqeqeq was fixed and committed.

2022-08-30 01:51 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
I was thinking the loading addition should be more similar to https://vuetifyjs.com/en/components/buttons/#loaders 
It removes the text inside while loading, shows a spinner, OR you also have the option to use the slot, which you could overwrite the spinner behavior with something like "loading..." text or whatnot. I simply think their solution looks nice and it's something we could mimic, since Bootstrap has no preference

2022-08-30 01:54 UTC, VividLemon commented
> I will take a look and try my best to follow it in any upcoming commits. Sorry if i am doing something wrong, It's my first time contributing an open-source library.

It's nothing detrimental, but it causes issues with the bot that parses through and automates the changelog file, and tag releases. For example, since the last one didn't contain the conventional commit, it didn't actually give any notice in the changelog. Which could be harmful to those updating. But after I got into using conventional commits after the decision to use them here, I exclusively use them on all projects now.

2022-08-30 02:30 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
I see, now it does look like a useful thing to have. There you go 
![image](https://user-images.githubusercontent.com/58523735/187334822-c66a6e5e-623c-45b5-9e74-ee437cce870b.png)

2022-08-30 02:43 UTC, VividLemon requested changes
Once that's done, I think it's at a great point to merge.

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButtonLoading.vue
> +const props = defineProps<Props>()
remove `const props =` when props is not used. Otherwise an eslint error will occur for no unused vars

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    loadingMode: {type: String as () => 'fill' | 'inline', default: 'inline'},
I think `String as PropType<'fill' | 'inline'>` may work better.

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButtonLoading.vue
> +    <slot v-if="loading">
The second v-if is redundant as it would not be rendered if the parent isn't rendered.

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButtonLoading.vue
> +    :class="{'mode-fill': mode == 'fill', 'mode-inline': mode == 'inline'}"
eqeqeq

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
>      loading: {type: Boolean, default: false},
```ts
type: [Boolean, String] as PropType<Booleanish>
```
And, of course, resolve the `Booleanish` to `boolean` by using the `useBooleanish()` function

2022-08-30 02:43 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButtonLoading.vue
> +type Props = {
```ts
interface Props {
loading?: Booleanish
mode?: 'fill' | 'inline'
size?: InputSize
}

const loadingBoolean = useBooleanish(toRef(prop, 'loading'))
```
Though, Booleanish option isn't too useful for an internal item, I guess if it's there >.>

2022-08-30 02:49 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BButton/BButton.vue
> +    <BSpinner v-if="loading" class="btn-spinner" :small="size != 'lg'"></BSpinner>
Looks great!

2022-08-30 02:53 UTC, VividLemon commented
I'm also kind of skeptical of the use of decomposed .vue files when they are only used in a single component. Tbh, the use of a nested BButtonLoaading makes testing a bit more difficult since in every test I would need to check for the existence of the sub-component, it may be different if the sub-component is a huge bit of logic, but it's overhead. It's up to preference I guess.

2022-08-30 03:19 UTC, VividLemon reviewed
Last fix

2022-08-30 03:21 UTC, devhus commented
> I'm also kind of skeptical of the use of decomposed .vue files when they are only used in a single component. Tbh, the use of a nested BButtonLoaading makes testing a bit more difficult since in every test I would need to check for the existence of the sub-component, it may be different if the sub-component is a huge bit of logic, but it's overhead. It's up to preference I guess.

BButtonLoading is removed, and your other suggestions are done 😄

2022-08-30 03:26 UTC, VividLemon commented
My last note must have been removed from the commit. But, be careful when using intellisense for importing 

Package imports are perfectly fine `import {ref} from 'vue'` is perfectly fine.

Routes like `import {type} from 'src/types' will break the component when in library mode. 

Not intuitive at all, but I've dealt with the problem before. Use relative paths when vite is in library mode

2022-08-30 03:30 UTC, merged

2022-08-30 03:30 UTC, devhus commented
> My last note must have been removed from the commit. But, be careful when using intellisense for importing
> 
> Package imports are perfectly fine `import {ref} from 'vue'` is perfectly fine.
> 
> Routes like `import {type} from 'src/types' will break the component when in library mode.
> 
> Not intuitive at all, but I've dealt with the problem before. Use relative paths when vite is in library mode
> 
> > I've used a child component so i don't increase the BButton component code
> 
> I get why you'd do it, decomposition of components is a good strategy, but sometimes it's better to not

Noted. 👍🏼