BContainer tag prop, BTable items/rows selection
cdmoro/bootstrap-vue-3 pull request #609
Opened 2022-08-30 23:37 UTC by devhus

BREAKING CHANGES: .container & .container-fluid CSS classes now have a default 'block' display to behave as a 'div' element when the BContainer tag is changed
BREAKING CHANGE: BTable 'sorted' event output value was changed to an object with keys [sort(string), desc(boolean)] for better ts type support.

fix: added a few missing props to the BTable.d.ts file
fix: replaced BTable emits definition array with a typescript interface for better type support

feat: Added 'tag' prop to BContainer component
feat: Added BTable selectable prop that adds the selection functionality to the table, Added select-mode prop with a value of [multi, single, range] to expand how the table selection can be used.
feat: Added Btable select-head prop to show an extra Head & Cell to the table
feat: Added selectHead & selectCell slots to customize the selection of the extra head & cells.

2022-08-30 23:43 UTC, devhus commented
A working example:
```vue
<template>
  <b-container class="py-4">
    <b-form-group
      label="Selection mode:"
      label-for="table-select-mode-select"
      label-cols-md="4"
    >
      <b-form-select
        id="table-select-mode-select"
        v-model="selectMode"
        :options="modes"
        class="mb-3"
      ></b-form-select>
    </b-form-group>

    <b-table
      :items="items"
      :fields="fields"
      :select-mode="selectMode"
      responsive="sm"
      ref="selectableTable"
      selectable
      @row-selected="onRowSelected"
      @row-unselected="onRowUnSelected"
      @selection="onSelection"
      :select-cell="false"
    >
      <template #selectHead>Is Selected?</template>
      <template #selectCell>✔</template>
      <!-- Example scoped slot for select state illustrative purposes -->
      <template #cell(selected)="{ rowSelected }">
        <template v-if="rowSelected">
          <span aria-hidden="true">&check;</span>
          <span class="sr-only">Selected</span>
        </template>
        <template v-else>
          <span aria-hidden="true">&nbsp;</span>
          <span class="sr-only">Not selected</span>
        </template>
      </template>
    </b-table>
    <p>
      Selected Rows:<br>
      {{ selected }}
    </p>
    <p>
      Internal Selected Rows:<br>
      {{ internalSelected }}
    </p>
  </b-container>
</template>

<script  lang="ts" >
import { defineComponent } from "vue";
import { BTableProps } from "./types/components";

export default defineComponent({
  data() {
    return {
      modes: ['multi', 'single', 'range'],
      fields: ['isActive', 'age', 'first_name', 'last_name'],
      items: [
        { isActive: true, age: 40, first_name: 'Dickerson', last_name: 'Macdonald' },
        { isActive: false, age: 21, first_name: 'Larsen', last_name: 'Shaw' },
        { isActive: false, age: 89, first_name: 'Geneva', last_name: 'Wilson' },
        { isActive: true, age: 38, first_name: 'Jami', last_name: 'Carney' }
      ],
      selectMode: 'multi' as BTableProps['selectMode'],
      selected: [],
      internalSelected: [],
    }
  },
  methods: {
    onRowSelected(item: any) {
      this.selected.push(item);
    },
    onRowUnSelected(item: any) {
      this.selected.splice(this.selected.indexOf(item), 1);
    },
    onSelection(items: any) {
      this.internalSelected = items;
    },
  }
});
</script>
```

More logic to be added later to give the ability to update selectedItems array through props using v-model, and provide few methods to control the internal selectedItems array (such as, selectAllRows, clearSelected, selectRow(index))

2022-08-31 00:23 UTC, VividLemon commented
If you could possibly address https://github.com/cdmoro/bootstrap-vue-3/pull/608. Feel free to give them a message, figure out a solution, or copy both the changes together, as to not have any merge conflicts.

2022-08-31 00:24 UTC, VividLemon commented
If you could possibly address https://github.com/cdmoro/bootstrap-vue-3/pull/608. Feel free to give them a message, figure out a solution, or copy both the changes together, as to not have any merge conflicts. @cattaneoinfoesse

2022-08-31 00:33 UTC, devhus commented
> If you could possibly address #608. Feel free to give them a message, figure out a solution, or copy both the changes together, as to not have any merge conflicts. @cattaneoinfoesse

done.

2022-08-31 00:50 UTC, VividLemon requested changes

2022-08-31 00:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
selectableBoolean.value

2022-08-31 00:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  selectable?: boolean
You included this as a `useBooleanish` option, but did not set the type to `Booleanish`. That and sortInternal, not that it was Booleanish though either. If you could handle all of them, ie sortDesc, sortInternal, selectable, that would be great.

2022-08-31 00:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  selectable?: boolean
sortInternal doesn't have a default value. Perhaps it should be false by default?

2022-08-31 00:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
!!props.selectHead
Just since it could be possible that things could get confused.

2022-08-31 00:50 UTC, VividLemon commented on packages/bootstrap-vue-3/src/types/components/BTable/BTable.d.ts
> +  sortInternal?: boolean
At this time you don't _technically_ need to bother with keeping this list updated. Once Vue supports type imports for props and emits, all the component .d.ts files will need to be updated.

2022-08-31 01:05 UTC, devhus commented on packages/bootstrap-vue-3/src/types/components/BTable/BTable.d.ts
> +  sortInternal?: boolean
noted

2022-08-31 01:06 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  selectable?: boolean
> You included this as a `useBooleanish` option, but did not set the type to `Booleanish`. That and sortInternal, not that it was Booleanish though either. If you could handle all of them, ie sortDesc, sortInternal, selectable, that would be great.

done


> sortInternal doesn't have a default value. Perhaps it should be false by default?

It has a default value as true, changed it to false.

2022-08-31 01:11 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
> !!props.selectHead Just since it could be possible that things could get confused.

Both the pro and slot doing kinda the same job, passing either of both will show/replace the select head & cells. 
The prop is a quicker method to change the header as a text.
The slot is a better method to change the element as a whole.

What is your suggestion?

2022-08-31 01:21 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  selectable?: boolean
> It has a default value as true, changed it to false

It did? I must have not seen it then

2022-08-31 01:27 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  (e: 'update:sortDesc', value: Booleanish): void
I think it's best to follow the practices of other components here. Basically, when a prop type is only `boolean` it can be converted to `Booleanish`, immediately in script it is resolved down to `boolean` and only the `useBooleanish` value is used throughout the script. 

Basically, I think you should convert this emit value back to `boolean`, and only use the resolved `boolean` values throughout the script, and never pass `Booleanish` values around. There's nothing wrong with passing them around, I think it's best to just keep everything on the same page and using pure `boolean` values.

2022-08-31 01:31 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
Do you mean for example that: 
```ts
<slot name="title">
   {{props.title}}
</slot>
```
is your issue here, and is redundant? Or that there is something wrong with this particular `||` statement? I'm a little confused.

2022-08-31 01:34 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  (e: 'update:sortDesc', value: Booleanish): void
done, now it does feel right.

2022-08-31 01:39 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
I got confused as well. I don't think there is an issue in that part, just trying to understand your point.
What is the issue here exactly?

2022-08-31 01:42 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
Since props.selectHead is type `boolean | string`, a compiler _could_ get confused by the string part. replacing `selectableBoolean.value && (props.selectHead || slots.selectHead !== undefined)` with `selectableBoolean.value && (!!props.selectHead || slots.selectHead !== undefined)` is "kinda, sorta, good enough" to ensure it checks against boolean values. Just js weirdness

2022-08-31 01:47 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
Like, doing something like 
```ts
interface Props {
someProp?: boolean | string
}
const classes = computed<Record<string, boolean>>(() => ({
   someClass: props.someProp
})
```
Would cause a ts error, since string can't resolve to boolean. This is just an example, but it illustrates the point. This is probably a non-issue since doing `foo && bar` should make everything boolean... but JS is weird

2022-08-31 01:49 UTC, devhus commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
Good, I've learned something new today.
It is done.

2022-08-31 01:55 UTC, VividLemon commented on packages/bootstrap-vue-3/src/components/BTable/BTable.vue
> +  () => selectableBoolean && (props.selectHead || slots.selectHead !== undefined)
It will still do something like this when is string:
```ts
const a = ''
console.log(!!a) // false
const b = 'a' // adding even a single character
console.log(!!b) // true
```
So doing !! might give a weird issue if a user ever passes an empty string, but I think it's usually expected.

2022-08-31 02:03 UTC, merged

2022-09-12 10:51 UTC, ahmedrazaa commented
seems working fine for me except to know one thing, how i can change icon for not selected item it always show ✔ for all rows.<template v-slot:cell(selected)="rowSelected ">
          
          <template v-if="rowSelected">
          <span aria-hidden="true">&check;</span>
          <span class="sr-only">Selected</span>
        </template>
        <template v-else>
          <span aria-hidden="true">&nbsp;</span>
          <span class="sr-only">Not selected</span>
        </template> 
       </template> 
it looks like that part of code isn't working, always show ✔ for all rows

2022-09-12 14:40 UTC, devhus commented
> seems working fine for me except to know one thing, how i can change icon for not selected item it always show ✔ for all rows.<template v-slot:cell(selected)="rowSelected ">
> 
> ```
>       <template v-if="rowSelected">
>       <span aria-hidden="true">&check;</span>
>       <span class="sr-only">Selected</span>
>     </template>
>     <template v-else>
>       <span aria-hidden="true">&nbsp;</span>
>       <span class="sr-only">Not selected</span>
>     </template> 
>    </template> 
> ```
> 
> it looks like that part of code isn't working, always show ✔ for all rows

with the upcoming release update, it will be customizable using CSS. Please take a look at #643

2022-09-12 14:53 UTC, VividLemon commented
I think it would be nice if additionally those values could be modified using slots, for those like me that don't like touching css.

2024-03-07 10:01 UTC, yashwp commented
I'm using `0.16.6` version of this package. But I cannot use `rowSelected` to render checkboxes for each row and select/deselect on row selection.

When I can expect this fix?

```
<b-table responsive hover :items="items" :fields="columns" tbody-tr-class="cursor-pointer"
               selectable select-mode="multi" @row-selected="onRowSelect" :select-head="true"
               @row-unselected="onRowDeselect">
        <template #cell(null)="{ rowSelected }">
          {{ rowSelected }}
          <input type="checkbox" :checked="rowSelected">
        </template>
      </b-table>
      ```

2024-05-16 08:13 UTC, noque-lind commented
Same issue for me on 17.6 as well!